##
#
#  Copyright Hans de Rooij 2024
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, 
#  software distributed under the License is distributed on an 
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
#  either express or implied. See the License for the specific 
#  language governing permissions and limitations under the 
#  License.
#
##

services:
   b2b_ah_pg:
      container_name: b2b_ah_pg

      image: postgres:16.2

      secrets:
         - pg_password

      environment:
         - POSTGRES_DB=${PG_DATABASE}
         - PGUSER=${PG_USER}
         - POSTGRES_PASSWORD_FILE=/run/secrets/pg_password

      restart: always

      volumes:
         - /var/lib/pg/data:/var/lib/postgresql/data
         - ./postgres/sql:/docker-entrypoint-initdb.d

      healthcheck:
         test: ["CMD-SHELL", "pg_isready"]
         interval: 10s
         timeout: 5s
         retries: 5

      ports:
         - 5432:5432

   b2b_api_hub:
      container_name: b2b_api_hub

      secrets:
         - pg_password
         - dnb_dpl_key
         - dnb_dpl_secret

      environment:
         - PG_HOST=${PG_HOST}
         - PG_DATABASE=${PG_DATABASE}
         - PG_USER=${PG_USER}
         - API_SERVER_PORT=${API_SERVER_PORT}

      build:
         context: ./node

      depends_on:
         b2b_ah_pg:
            condition: service_healthy

      ports:
         - 8088:${API_SERVER_PORT}

secrets:
   pg_password:
      file: ${HOME}/.secrets/pg_password
   dnb_dpl_key:
      file: ${HOME}/.secrets/dnb_dpl_key
   dnb_dpl_secret:
      file: ${HOME}/.secrets/dnb_dpl_secret
